version: 0.2

phases:
  install:
    runtime-versions:
      nodejs: 16
    commands:
      - echo installing nodejs...

  pre_build:
    commands:
      - echo installing dependencies...
      - npm install

  build:
    commands:
      - echo testing...
      - npm run build
      # - echo building...
      # - ng build

artifacts:
  files:
    - "**/*"
  discard-paths: no
  base-directory: dist/weathermapapp
